### ISSUE TITLE
More components

### ISSUE THREAD

**Issue by mjmarques97** [Bellafaire/CircuiTikZ-Tool#4]
For power electronics applications the IGBT with the body diode and the transformer are essential components. Mind adding those?

The IGBT should be easy as it is a transistor, like the PNP and the NPN. The transformer is a little bit more tricky.

Thank you so much for your hard work!

**Comment by Bellafaire** [comment]
IGBT and Transformers have been added as templates to the program. I appreciate the feedback, if you have any further suggestions feel free to post them here. 

Please use "enhanement" tag for feature requests and "bug" tags for issues with the software.
